# Copyright 2018 The Kubernetes Authors.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: Upgrade pip to latest
  ansible.builtin.pip:
    name: pip
    executable: pip3
    state: latest

- name: Install aws clients
  ansible.builtin.pip:
    name: "{{ packages }}"
    executable: pip3
  vars:
    packages:
      - awscli
  when: ansible_distribution != "Amazon" and ansible_distribution != "RedHat"

- ansible.builtin.include_tasks: awscliv2.yml
  when: ansible_distribution == "RedHat"

# Remove after https://github.com/aws/amazon-ssm-agent/issues/235 is fixed.
- name: Install aws agents RPM on Redhat distributions
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    disable_gpg_check: true
  with_items:
    - "{{ amazon_ssm_agent_rpm }}"
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution != "Amazon"

- name: Install aws agents RPM
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - amazon-ssm-agent
    - awscli
  when: ansible_distribution == "Amazon"

- name: Ensure ssm agent is running RPM
  ansible.builtin.service:
    name: amazon-ssm-agent
    state: started
    enabled: true
  when: ansible_os_family == "RedHat"

- name: Install aws agents Ubuntu
  ansible.builtin.shell: snap install amazon-ssm-agent --classic
  when: ansible_distribution == "Ubuntu"

- name: Ensure ssm agent is running Ubuntu
  ansible.builtin.service:
    name: snap.amazon-ssm-agent.amazon-ssm-agent.service
    state: started
    enabled: true
  when: ansible_distribution == "Ubuntu"

- name: Disable Hyper-V KVP protocol daemon on Ubuntu
  ansible.builtin.systemd:
    name: hv-kvp-daemon
    state: stopped
    enabled: false
  when: ansible_os_family == "Debian"
