# Copyright 2020 The Kubernetes Authors.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: Add debug tools directory
  win_file:
    path:  '{{ kubernetes_install_path }}\debug'
    state: directory
    
- name: Get debug files
  win_get_url:
    url:  '{{ item }}'
    dest: '{{ kubernetes_install_path }}\debug\'
  loop: 
    - "https://github.com/Microsoft/SDN/raw/master/Kubernetes/flannel/l2bridge/cni/win-bridge.exe"
    - "https://github.com/microsoft/SDN/raw/master/Kubernetes/windows/debug/collectlogs.ps1"
    - "https://github.com/microsoft/SDN/raw/master/Kubernetes/windows/debug/dumpVfpPolicies.ps1"
    - "https://github.com/microsoft/SDN/raw/master/Kubernetes/windows/debug/portReservationTest.ps1"
    - "https://github.com/microsoft/SDN/raw/master/Kubernetes/windows/debug/starthnstrace.cmd"
    - "https://github.com/microsoft/SDN/raw/master/Kubernetes/windows/debug/startpacketcapture.cmd"
    - "https://github.com/microsoft/SDN/raw/master/Kubernetes/windows/debug/stoppacketcapture.cmd"
    - "https://github.com/Microsoft/SDN/raw/master/Kubernetes/windows/debug/VFP.psm1"
    - "https://github.com/microsoft/SDN/raw/master/Kubernetes/windows/helper.psm1"
    - "https://github.com/Microsoft/SDN/raw/master/Kubernetes/windows/hns.psm1"
