# Copyright 2018 The Kubernetes Authors.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
common_rpms:
- yum-utils
- python2-pip
- python-requests
- ebtables
- socat
- ntp
- jq
- nfs-utils
common_extra_rpms: []
common_debs:
- openssh-client
- openssh-server
- apt-transport-https
- ebtables
- socat
- ntp
- jq
- nfs-client

common_pinned_debs: []
common_extra_debs: []
common_redhat_epel_rpm: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
disable_public_repos: false
extra_repos: ""
common_photon_rpms: "python3-pip python-requests ebtables socat ntp jq nfs-utils net-tools conntrack-tools distrib-compat"
#photon does not have backward compatibility for legacy distro behavior for sysctl.conf by default
#as it uses systemd-sysctl. set this var so we can use for sysctl conf file value.
sysctl_conf_file: "{{ '/etc/sysctl.d/99-sysctl.conf' if ansible_os_family == 'VMware Photon OS' else '/etc/sysctl.conf' }}"
