# Copyright 2020 The Kubernetes Authors.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- ansible.builtin.include_tasks: bootstrap-flatcar.yml

- name: Create system-environment-generators directory
  ansible.builtin.file:
    path: /etc/systemd/system-environment-generators
    state: directory

- name: Add env generator that includes system PATH on service path
  ansible.builtin.copy:
    src: etc/systemd/system-environment-generators/10-flatcar-path
    dest: /etc/systemd/system-environment-generators/10-flatcar-path
    owner: root
    group: root
    mode: "0755"

- name: Enable systemd-timesyncd unit
  ansible.builtin.systemd:
    enabled: true
    name: systemd-timesyncd.service
