# Copyright 2020 The Kubernetes Authors.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
kubernetes_base_url: https://dl.k8s.io/release/v1.19.2/bin/windows/amd64
cloudbase_init_url: https://github.com/cloudbase/cloudbase-init/releases/download/1.1.2/CloudbaseInitSetup_1_1_2_x64.msi
nssm_url: https://azurek8scishared.blob.core.windows.net/nssm/nssm.exe
gmsa_keyvault_url: https://kubernetesartifacts.azureedge.net/ccgakvplugin/v1.1.4/binaries/windows-gmsa-ccgakvplugin-v1.1.4.zip

runtime: containerd
kubernetes_install_path: c:\k
windows_service_manager: nssm
pause_image: registry.k8s.io/pause:3.9
load_additional_components: true
additional_registry_images: true
additional_registry_images_list: sigwindowstools/kube-proxy:v1.28.4-calico-hostprocess, sigwindowstools/calico-node:v3.26.1-hostprocess
prepull: false
distribution_version: 2019

cloudbase_metadata_services: cloudbaseinit.metadata.services.azureservice.AzureService, cloudbaseinit.metadata.services.ovfservice.OvfService
cloudbase_plugins: cloudbaseinit.plugins.common.ephemeraldisk.EphemeralDiskPlugin, cloudbaseinit.plugins.common.userdata.UserDataPlugin, cloudbaseinit.plugins.common.localscripts.LocalScriptsPlugin
cloudbase_metadata_services_unattend: cloudbaseinit.metadata.services.azureservice.AzureService, cloudbaseinit.metadata.services.ovfservice.OvfService
cloudbase_plugins_unattend: cloudbaseinit.plugins.common.mtu.MTUPlugin

debug_tools: true
additional_debug_files: https://raw.githubusercontent.com/kubernetes-sigs/sig-windows-tools/master/hack/DebugWindowsNode.ps1
